### ISSUE TITLE
no documentation

### ISSUE THREAD

**Issue by blargomat** [tansey/poker#1]
dafuq?

**Comment by tansey** [comment]
This is a really old repo that I don't maintain anymore and it was only ever really experimental/research ideas. If you want to do something equivalent, I would suggest using the holdem_engine (https://github.com/tansey/holdem_engine) and other libraries that do have some documentation. I definitely wouldn't recommend using evolutionary algorithms though, as that's not likely to develop a good agent, for a host of reasons. If you're interested in poker AI research, see my CFR repo (https://github.com/tansey/pycfr) for a game theoretic approach to poker. Multi-agent poker is still a really tough game though and you can't just find a Nash equilibrium like in 2-player games. Still, that's where I'd start if I were you.
